{
 "title": "AQDC dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Home humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(humidity) AS \"home_dht22\"\nFROM home_dht22\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obsTime,$__interval),\n  avg(HUMD) AS \"outdoor\"\nFROM cwb_Taichung\nWHERE\n  $__timeFilter(obsTime)\nGROUP BY 1\nORDER BY $__timeGroup(obsTime,$__interval)"
    }
   ]
  },
  {
   "title": "Home Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(temperature) AS \"dht22\"\nFROM home_dht22\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(temperature) AS \"ds18b20\"\nFROM home_ds18b20\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obsTime,$__interval),\n  avg(TEMP) AS \"outdoor\"\nFROM cwb_Taichung\nWHERE\n  $__timeFilter(obsTime)\nGROUP BY 1\nORDER BY $__timeGroup(obsTime,$__interval)"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgNm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m),\n  avg(pm2_5) AS \"room\"\nFROM home_pms7003\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(PM2_5) AS \"outdoor\"\nFROM epa_Taipei\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "PM10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgNm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m),\n  avg(pm10) AS \"pm10\"\nFROM home_pms7003\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  PM10 AS \"outdoor\"\nFROM epa_Taipei\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "SL Server temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obsTime,$__interval),\n  avg(TEMP) AS \"TEMP\"\nFROM cwb_Taitung\nWHERE\n  $__timeFilter(obsTime)\nGROUP BY 1\nORDER BY $__timeGroup(obsTime,$__interval)"
    }
   ]
  },
  {
   "title": "SL Server humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obsTime,$__interval),\n  avg(HUMD) AS \"pm1\"\nFROM cwb_Taitung\nWHERE\n  $__timeFilter(obsTime)\nGROUP BY 1\nORDER BY $__timeGroup(obsTime,$__interval)"
    }
   ]
  },
  {
   "title": "indoor temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m),\n  avg(temperature) AS \"temperature\"\nFROM home_ds18b20\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1m)"
    }
   ]
  },
  {
   "title": "indoor humid",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m),\n  avg(humidity) AS \"temperature\"\nFROM home_dht22\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1m)"
    }
   ]
  }
 ]
}