{
 "title": "AQDC",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Outdoor Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obsTime,5m),\n  avg(TEMP) AS \"TEMP\"\nFROM cwb_Taichung\nWHERE\n  $__timeFilter(obsTime)\nGROUP BY 1\nORDER BY $__timeGroup(obsTime,5m)"
    }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m),\n  avg(temperture) AS \"temperture\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m)"
    }
   ]
  },
  {
   "title": "Room Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  humidity\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Room CO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m),\n  avg(CO2) AS \"CO2\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m)"
    }
   ]
  },
  {
   "title": "Room TVOC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,5m),\n  avg(TVOC) AS \"TVOC\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,5m)"
    }
   ]
  },
  {
   "title": "Room PM2.5",
   "type": "gauge",
   "description": "顏色依照環保署空氣品質監測網標示",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(PM2_5) AS \"PM2.5\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Room PM10",
   "type": "gauge",
   "description": "顏色依照環保署空氣品質監測網標示",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(PM10) AS \"PM10\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Temperture",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m),\n  avg(temperture) AS \"temperture\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1m)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obsTime,$__interval),\n  avg(TEMP) AS \"Taichung\"\nFROM cwb_Taichung\nWHERE\n  $__timeFilter(obsTime)\nGROUP BY 1\nORDER BY $__timeGroup(obsTime,$__interval)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m),\n  avg(humidity) AS \"Home\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,1m)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obsTime,$__interval),\n  avg(HUMD) AS \"Taichung\"\nFROM cwb_Taichung\nWHERE\n  $__timeFilter(obsTime)\nGROUP BY 1\nORDER BY $__timeGroup(obsTime,$__interval)"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(CO2) AS \"Home\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "TVOC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(TVOC) AS \"Home\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  PM2_5 AS \"Room\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(PM2_5) AS \"Taichung\"\nFROM epa_Taichung\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "PM10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(PM10) AS \"Room\"\nFROM sensor_data\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(PM10) AS \"Taichung\"\nFROM epa_Taichung\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  }
 ]
}